
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[185] =
    {   0,
        0,    0,   75,   74,    1,   74,   74,   43,    3,    4,
       40,   38,   17,   39,   16,   41,   71,   18,   10,   15,
        9,   70,    7,    8,   42,   70,   70,   70,   70,   70,
       70,   70,   67,   70,   70,   70,   70,   70,   70,   69,
       70,   70,    5,    6,    1,   14,    0,   73,   72,    0,
        0,   71,   12,   13,   11,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   65,   70,
       70,   70,   33,   27,   70,   57,   70,   70,   45,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,    0,    0,    0,   53,   44,   70,   70,   70,

       70,   70,   70,   48,   66,   52,   50,   70,   70,   70,
       70,   31,   70,   19,   70,   70,   58,   46,   70,   70,
       70,   70,   51,   47,   70,   70,   21,   70,   49,   70,
       64,   70,   70,    0,   72,    2,   70,   22,   70,   55,
       62,   70,   70,   35,   70,   70,   70,   70,   37,   70,
       70,   70,   61,   60,   56,   70,   34,   70,   70,   24,
       29,   70,   70,   59,   54,   70,   70,   36,   63,   70,
       25,   70,   32,   70,   20,   70,   68,   30,   23,   70,
       70,   28,   26,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   20,   20,   20,   21,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       22,    1,   23,   24,   25,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   20,   35,   36,   20,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   20,
       20,   47,   48,    1,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    4,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    5,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1
    } ;

static const flex_int16_t yy_base[188] =
    {   0,
        0,    0,  209,  210,   48,  190,  202,  210,  210,  210,
      210,  210,  210,  210,  191,  196,   39,  210,  186,  185,
      184,    0,  210,  210,  210,   26,   19,   26,  163,   22,
       34,   28,  175,   24,  161,  157,  156,   45,   46,   48,
       47,  163,  210,  210,   82,  210,  190,  189,   67,  184,
      177,   77,  210,  210,  210,    0,  149,  161,  151,  150,
      157,  152,   57,  157,  152,  139,  140,  145,    0,  142,
      138,  141,    0,  134,  134,    0,   69,  132,    0,  140,
      136,  129,  125,  142,   59,  128,  127,   71,  137,  125,
      137,  130,   95,  154,  148,    0,    0,  133,  124,  133,

      122,  115,  113,    0,    0,    0,    0,  128,  124,  123,
      114,    0,  123,    0,  107,  120,    0,    0,  111,  115,
      102,  103,    0,    0,  114,  100,    0,  106,    0,  104,
        0,   97,  103,  123,  122,  210,  101,    0,  100,    0,
        0,  100,   97,    0,   91,   90,   87,  103,    0,   85,
       97,   85,    0,    0,    0,   95,    0,   86,   93,    0,
        0,   85,   91,    0,    0,   79,   68,    0,    0,   67,
        0,   62,    0,   56,    0,   53,    0,    0,    0,   57,
       42,    0,    0,  210,  110,  112,  116
    } ;

static const flex_int16_t yy_def[188] =
    {   0,
      184,    1,  184,  184,  184,  184,  185,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  186,  184,  184,  184,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  184,  184,  184,  184,  185,  185,  184,  187,
      184,  184,  184,  184,  184,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  184,  187,  184,  186,  186,  186,  186,  186,

      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  184,  184,  184,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,    0,  184,  184,  184
    } ;

static const flex_int16_t yy_nxt[260] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   24,   25,    4,   26,   27,   28,   29,   30,
       31,   22,   22,   32,   33,   34,   35,   36,   37,   22,
       38,   39,   40,   22,   41,   42,   22,   43,   44,   45,
       45,   51,   57,   52,   59,   62,   60,   67,   73,   61,
       76,   77,   58,   63,   74,   68,   69,   64,   65,   70,
       81,   71,   90,   88,   82,   84,   91,   72,  183,   85,
       89,   49,   83,   45,   45,   86,  182,   93,   87,   51,
      181,   52,  102,  103,  116,  124,   93,  128,  104,  180,

      117,  105,  179,  178,  134,  125,  134,  129,  177,  135,
       47,   47,  176,   47,   47,   56,   56,   94,   94,   94,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  135,  135,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,   95,  133,  132,  131,  130,  127,  126,  123,
      122,  121,  120,  119,  118,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  101,  100,   99,   98,   97,
       96,   49,   95,   48,   48,   92,   80,   79,   78,   75,

       66,   55,   54,   53,   50,   49,   48,   46,  184,    3,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184
    } ;

static const flex_int16_t yy_chk[260] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,   17,   26,   17,   27,   28,   27,   30,   32,   27,
       34,   34,   26,   28,   32,   30,   30,   28,   28,   31,
       38,   31,   41,   40,   38,   39,   41,   31,  181,   39,
       40,   49,   38,   45,   45,   39,  180,   49,   39,   52,
      176,   52,   63,   63,   77,   85,   49,   88,   63,  174,

       77,   63,  172,  170,   93,   85,   93,   88,  167,   93,
      185,  185,  166,  185,  185,  186,  186,  187,  187,  187,
      163,  162,  159,  158,  156,  152,  151,  150,  148,  147,
      146,  145,  143,  142,  139,  137,  135,  134,  133,  132,
      130,  128,  126,  125,  122,  121,  120,  119,  116,  115,
      113,  111,  110,  109,  108,  103,  102,  101,  100,   99,
       98,   95,   94,   92,   91,   90,   89,   87,   86,   84,
       83,   82,   81,   80,   78,   75,   74,   72,   71,   70,
       68,   67,   66,   65,   64,   62,   61,   60,   59,   58,
       57,   51,   50,   48,   47,   42,   37,   36,   35,   33,

       29,   21,   20,   19,   16,   15,    7,    6,    3,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical_analizer.l"
#line 2 "lexical_analizer.l"
/* definitions of manifest constants */
#define COMMENT 401
#define OPENING_PAR 402
#define CLOSING_PAR 403
#define OPENING_BR 404
#define CLOSING_BR 405
#define OPENING_SBR 406
#define CLOSING_SBR 407
#define ASSIGN_OP 408
#define DOT 409
#define COMMA 410
#define SEMICOLON 411
#define INT 101
#define DOUBLE 102
#define STR 103
#define BOOL 104
#define VECTOR 105
#define BLOCK 106
#define TABLE 107
#define DATA_TYPE 501
#define FUNCTION 502
#define IN 503
#define CONTINUE 504
#define BREAK 505
#define RETURN 506
#define FOR 507
#define WHILE 508
#define IF 509
#define THEN 510
#define ELSE 511
#define PRINT 512
#define LOAD 513
#define GT 108
#define LT 109
#define GE 110
#define LE 111
#define EQ 112
#define NE 113
#define RELAT_OP 514
#define ADD 114
#define SUB 115
#define MUL 116
#define DIV 117
#define POW 118
#define MOD 119
#define ARITME_OP 515
#define AND 120
#define OR 121
#define NOT 122
#define LOGICAL_OP 516
#define SIN 123
#define COS 124
#define TAN 125
#define CTG 126
#define SEC 127
#define CSC 128
#define ABS 129
#define FLOOR 130
#define VARIANCE 523
#define EXPECTED_VALUE 524
#define COVARIANCE 525
#define K 526
#define K_STAR 527
#define T 528
#define CEIL 131
#define SQRT 132
#define LN 133
#define LOG 134
#define EULER 135
#define MATH_FUNC 517
#define ID 518
#define I_NUMBER 601
#define R_NUMBER 602
#define STRING 603
#define SIZE 519
#define ROWS 520
#define COLS 521
#define RANGE 522
#define VARIANCE 523
#define EXPECTED_VALUE 524
#define COVARIANCE 525
#define K 526
#define K_STAR 527
#define T 528

/* required libraries */
#include <stdio.h>
#include <errno.h>
#include <string.h>

/* symbol tables - current position */
unsigned int current_tid = 0;
unsigned int current_tnum = 0;
unsigned int current_tstr = 0;

typedef struct symbol_table {
    char **elements;
    int capacity;
    int size;
} symbol_table;

#define INITIAL_CAPACITY 10
#define MAX_TOSTRING 1024
#define MAX_STRING_VALUE 32

symbol_table* new_symbol_table() {
    symbol_table *list = (symbol_table*) malloc(sizeof(symbol_table));
    list->elements = (char**) malloc(INITIAL_CAPACITY * sizeof(char*));
    list->capacity = INITIAL_CAPACITY;
    list->size = 0;
    return list;
}

void insert(symbol_table *table, int index, char* value) {
    if (index < 0 || index > table->size) {
        perror("Invalid index.\n");
        exit(EXIT_FAILURE);
    }
    if (table->size == table->capacity) {
        char **new_array = (char**) malloc(2 * table->capacity * sizeof(char*));
        for (int i = 0; i < table->size; i++) {
            new_array[i] = table->elements[i];
        }
        table->capacity *= 2;
        table->elements = new_array;
    }
    for (int i = table->size; i >= index; i--) {
        table->elements[i] = table->elements[i - 1];
    }
    table->elements[index] = value;
    table->size++;
}

void add_entry(symbol_table *table, char* value) {
    insert(table, table->size, value);
}

int find(symbol_table *table, char* element) {
    for (int i = 0; i < table->size; i++)
        if (strcmp(table->elements[i], element) == 0) {
            return i;
        }
    return -1;
}

void print_elements(symbol_table *table) {
   if (table->size == 0) {
        fprintf(yyout, "[]\n");
    } else {
        for (int i = 0; i < table->size; i++) {
            fprintf(yyout, "[%d] -> %s\n", i, table->elements[i]);
        }
    }
}

/* symbol tables for ids, numbers and strings */
symbol_table *id_table;
symbol_table *number_table;
symbol_table *string_table;
#line 716 "lex.yy.c"
/* regular definitions */
#line 718 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 174 "lexical_analizer.l"


#line 938 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 185 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 210 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 176 "lexical_analizer.l"
{/* no action and no return */}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 177 "lexical_analizer.l"
{write_token(COMMENT); return COMMENT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 178 "lexical_analizer.l"
{write_token(OPENING_PAR); return OPENING_PAR;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 179 "lexical_analizer.l"
{write_token(CLOSING_PAR); return CLOSING_PAR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 180 "lexical_analizer.l"
{write_token(OPENING_BR); return OPENING_BR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 181 "lexical_analizer.l"
{write_token(CLOSING_BR); return CLOSING_BR;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 182 "lexical_analizer.l"
{write_token(OPENING_SBR); return OPENING_SBR;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 183 "lexical_analizer.l"
{write_token(CLOSING_SBR); return CLOSING_SBR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 184 "lexical_analizer.l"
{write_token(GT); return RELAT_OP;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 185 "lexical_analizer.l"
{write_token(LT); return RELAT_OP;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 186 "lexical_analizer.l"
{write_token(GE); return RELAT_OP;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 187 "lexical_analizer.l"
{write_token(LE); return RELAT_OP;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 188 "lexical_analizer.l"
{write_token(EQ); return RELAT_OP;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 189 "lexical_analizer.l"
{write_token(NE); return RELAT_OP;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 190 "lexical_analizer.l"
{write_token(ASSIGN_OP); return ASSIGN_OP;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 191 "lexical_analizer.l"
{write_token(DOT); return DOT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 192 "lexical_analizer.l"
{write_token(COMMA); return COMMA;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 193 "lexical_analizer.l"
{write_token(SEMICOLON); return SEMICOLON;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 194 "lexical_analizer.l"
{write_token(INT); return DATA_TYPE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 195 "lexical_analizer.l"
{write_token(DOUBLE); return DATA_TYPE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 196 "lexical_analizer.l"
{write_token(STR); return DATA_TYPE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 197 "lexical_analizer.l"
{write_token(BOOL); return DATA_TYPE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 198 "lexical_analizer.l"
{write_token(VECTOR); return DATA_TYPE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 199 "lexical_analizer.l"
{write_token(BLOCK); return DATA_TYPE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 200 "lexical_analizer.l"
{write_token(TABLE); return DATA_TYPE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 201 "lexical_analizer.l"
{write_token(FUNCTION); return FUNCTION;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 202 "lexical_analizer.l"
{write_token(IN); return IN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 203 "lexical_analizer.l"
{write_token(CONTINUE); return CONTINUE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 204 "lexical_analizer.l"
{write_token(BREAK); return BREAK;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 205 "lexical_analizer.l"
{write_token(RETURN); return RETURN;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 206 "lexical_analizer.l"
{write_token(FOR); return FOR;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 207 "lexical_analizer.l"
{write_token(WHILE); return WHILE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 208 "lexical_analizer.l"
{write_token(IF); return IF;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 209 "lexical_analizer.l"
{write_token(THEN); return THEN;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 210 "lexical_analizer.l"
{write_token(ELSE); return ELSE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 211 "lexical_analizer.l"
{write_token(PRINT); return PRINT;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 212 "lexical_analizer.l"
{write_token(LOAD); return LOAD;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 213 "lexical_analizer.l"
{write_token(ADD); return ARITME_OP;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 214 "lexical_analizer.l"
{write_token(SUB); return ARITME_OP;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 215 "lexical_analizer.l"
{write_token(MUL); return ARITME_OP;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 216 "lexical_analizer.l"
{write_token(DIV); return ARITME_OP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 217 "lexical_analizer.l"
{write_token(POW); return ARITME_OP;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 218 "lexical_analizer.l"
{write_token(MOD); return ARITME_OP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 219 "lexical_analizer.l"
{write_token(AND); return LOGICAL_OP;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 220 "lexical_analizer.l"
{write_token(OR); return LOGICAL_OP;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 221 "lexical_analizer.l"
{write_token(NOT); return LOGICAL_OP;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 222 "lexical_analizer.l"
{write_token(SIN); return MATH_FUNC;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 223 "lexical_analizer.l"
{write_token(COS); return MATH_FUNC;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 224 "lexical_analizer.l"
{write_token(TAN); return MATH_FUNC;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 225 "lexical_analizer.l"
{write_token(CTG); return MATH_FUNC;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 226 "lexical_analizer.l"
{write_token(SEC); return MATH_FUNC;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 227 "lexical_analizer.l"
{write_token(CSC); return MATH_FUNC;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 228 "lexical_analizer.l"
{write_token(ABS); return MATH_FUNC;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 229 "lexical_analizer.l"
{write_token(FLOOR); return MATH_FUNC;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 230 "lexical_analizer.l"
{write_token(CEIL); return MATH_FUNC;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 231 "lexical_analizer.l"
{write_token(SQRT); return MATH_FUNC;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 232 "lexical_analizer.l"
{write_token(LN); return MATH_FUNC;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 233 "lexical_analizer.l"
{write_token(LOG); return MATH_FUNC;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 234 "lexical_analizer.l"
{write_token(EULER); return MATH_FUNC;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 235 "lexical_analizer.l"
{write_token(SIZE); return SIZE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 236 "lexical_analizer.l"
{write_token(ROWS); return ROWS;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 237 "lexical_analizer.l"
{write_token(COLS); return COLS;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 238 "lexical_analizer.l"
{write_token(RANGE); return RANGE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 239 "lexical_analizer.l"
{write_token(VARIANCE); return MATH_FUNC;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 240 "lexical_analizer.l"
{write_token(EXPECTED_VALUE); return MATH_FUNC;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 241 "lexical_analizer.l"
{write_token(COVARIANCE); return MATH_FUNC;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 242 "lexical_analizer.l"
{write_token(K); return MATH_FUNC;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 243 "lexical_analizer.l"
{write_token(K_STAR); return MATH_FUNC;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 244 "lexical_analizer.l"
{write_token(T); return MATH_FUNC;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 245 "lexical_analizer.l"
{install_id(); return ID;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 246 "lexical_analizer.l"
{install_number(0); return I_NUMBER;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 247 "lexical_analizer.l"
{install_number(1); return R_NUMBER;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 248 "lexical_analizer.l"
{install_string(); return STRING;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 250 "lexical_analizer.l"
ECHO;
	YY_BREAK
#line 1367 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 185 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 185 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 184);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 250 "lexical_analizer.l"


/*
    yytext -> pointer to the beginning of the lexeme
    yyleng -> length of the lexeme found
    yylval -> shared variable with YACC, it holds the lexeme's attribute (simulate)
    TODO:
    -> Complete vocabulary and lexical categories with friedman's test
*/

/* code represents the token, entry represents the attr */
void write_token(int code) {
    switch (code) {
        case 401:
            fprintf(yyout, "<comment>\n");
            break;
        case 402:
            fprintf(yyout, "<'('>\n");
            break;
        case 403:
            fprintf(yyout, "<')'>\n");
            break;
        case 404:
            fprintf(yyout, "<'{'>\n");
            break;
        case 405:
            fprintf(yyout, "<'}'>\n");
            break;
        case 406:
            fprintf(yyout, "<'['>\n");
            break;
        case 407:
            fprintf(yyout, "<']'>\n");
            break;
        case 408:
            fprintf(yyout, "<'='>\n");
            break;
        case 409:
            fprintf(yyout, "<'.'>\n");
            break;
        case 410:
            fprintf(yyout, "<','>\n");
            break;
        case 411:
            fprintf(yyout, "<';'>\n");
            break;
        case 101:
        case 102:
        case 103:
        case 104:
        case 105:
        case 106:
        case 107:
            fprintf(yyout, "<data_type, %s>\n", yytext);
            break;
        case 502:
            fprintf(yyout, "<function>\n");
            break;
        case 503:
            fprintf(yyout, "<in>\n");
            break;
        case 504:
            fprintf(yyout, "<continue>\n");
            break;
        case 505:
            fprintf(yyout, "<break>\n");
            break;
        case 506:
            fprintf(yyout, "<return>\n");
            break;
        case 507:
            fprintf(yyout, "<for>\n");
            break;
        case 508:
            fprintf(yyout, "<while>\n");
            break;
        case 509:
            fprintf(yyout, "<if>\n");
            break;
        case 510:
            fprintf(yyout, "<then>\n");
            break;
        case 511:
            fprintf(yyout, "<else>\n");
            break;
        case 512:
            fprintf(yyout, "<print>\n");
            break;
        case 513:
            fprintf(yyout, "<load>\n");
            break;
        case 108:
        case 109:
        case 110:
        case 111:
        case 112:
        case 113:
            fprintf(yyout, "<relat_op, '%s'>\n", yytext);
            break;
        case 114:
        case 115:
        case 116:
        case 117:
        case 118:
        case 119:
            fprintf(yyout, "<aritme_op, '%s'>\n", yytext);
            break;
        case 120:
        case 121:
        case 122:
            fprintf(yyout, "<logical_op, '%s'>\n", yytext);
            break;
        case 123:
        case 124:
        case 125:
        case 126:
        case 127:
        case 128:
        case 129:
        case 130:
        case 131:
        case 132:
        case 133:
        case 134:
        case 135:
        case 523:
        case 524:
        case 525:
        case 526:
        case 527:
        case 528:
            fprintf(yyout, "<math_func, '%s'>\n", yytext);
            break;
        case 519:
            fprintf(yyout, "<size>\n");
            break;
        case 520:
            fprintf(yyout, "<rows>\n");
            break;
        case 521:
            fprintf(yyout, "<cols>\n");
            break;
        case 522:
            fprintf(yyout, "<range>\n");
            break;
        default:
            perror("Code not recognized\n");
            exit(EXIT_FAILURE);
    }
}

char* get_lexeme() {
    char *result = malloc(yyleng);
    for (int i = 0; i < yyleng; i++) {
        result[i] = yytext[i];
    }
    return result;
}

/* function for install an id token in the symbol table */
int install_id() {
    char* lexeme = get_lexeme();
    int find_lexeme = find(id_table, lexeme);
    if (find_lexeme != -1) {
        fprintf(yyout, "<id, %d>\n", find_lexeme);
        return find_lexeme;
    }
    add_entry(id_table, lexeme);
    fprintf(yyout, "<id, %d>\n", current_tid);
    current_tid++;
    return current_tid - 1;
}

/* function for install a number token in the symbol table */
int install_number(int type) {
    char* lexeme = get_lexeme();
    int find_lexeme = find(number_table, lexeme);
    if (find_lexeme != -1) {
        if (type == 0) {
            fprintf(yyout, "<i_number, %d>\n", find_lexeme);
        } else {
            fprintf(yyout, "<r_number, %d>\n", find_lexeme);
        }
        return find_lexeme;
    }
    add_entry(number_table, lexeme);
    if (type == 0) {
        fprintf(yyout, "<i_number, %d>\n", current_tnum);
    } else {
        fprintf(yyout, "<r_number, %d>\n", current_tnum);
    }
    current_tnum++;
    return current_tnum - 1;
}

/* function for install a string token in the symbol table */
int install_string() {
    char* lexeme = get_lexeme();
    int find_lexeme = find(string_table, lexeme);
    if (find_lexeme != -1) {
        fprintf(yyout, "<string, %d>\n", find_lexeme);
        return find_lexeme;
    }
    add_entry(string_table, lexeme);
    fprintf(yyout, "<string, %d>\n", current_tstr);
    current_tstr++;
    return current_tstr - 1;
}

/*
    main function:
    -> open input & output files (if an error arise it stops
    the program execution)
    -> call the function yylex() to start lexical analysis
    -> close input & output streams
*/
int main(int argc, char* argv[]) {
    /*if (argc < 2) {
        perror("Not enough arguments.\n");
        exit(EXIT_FAILURE);
    }*/

    id_table = new_symbol_table();
    number_table = new_symbol_table();
    string_table = new_symbol_table();

    FILE *input;
    FILE *output;

    input = fopen("program.txt", "r");
    if (!input) {
        perror("Could not read input file.\n");
        exit(EXIT_FAILURE);
    }
    yyin = input;

    output = fopen("lex_analysis.out", "w");
    if (!output) {
        perror("Could not open output file.\n");
        exit(EXIT_FAILURE);
    }
    yyout = output;

    while (yylex()) {}
    fclose(yyin);

    fprintf(yyout, "\nSymbol table - ids\n");
    print_elements(id_table);
    fprintf(yyout, "\nSymbol table - numbers\n");
    print_elements(number_table);
    fprintf(yyout, "\nSymbol table - strings\n");
    print_elements(string_table);
    fclose(yyout);

    return 0;
}
